# Generated by Django 4.2.4 on 2023-11-27 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('about', models.TextField()),
                ('type', models.CharField(choices=[('It', 'It'), ('notIt', 'non it'), ('mobile', 'mobile')], max_length=50)),
                ('added_data', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
